offre_index:
    path:     /
    defaults: { _controller: "OffreBundle:Offre:index" }
    methods:  GET

offre_show:
    path:     /{id}/show
    defaults: { _controller: "OffreBundle:Offre:show" }
    methods:  GET

offre_new:
    path:     /new
    defaults: { _controller: "OffreBundle:Offre:new" }
    methods:  [GET, POST]

offre_edit:
    path:     /{id}/edit
    defaults: { _controller: "OffreBundle:Offre:edit" }
    methods:  [GET, POST]

offre_delete:
    path:     /{id}/delete
    defaults: { _controller: "OffreBundle:Offre:delete" }
    methods:  DELETE
