# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    OffreBundle\Security\OffreVoter:
        class: OffreBundle\Security\OffreVoter
        tags:
           - { name: security.voter }
        public: false
        arguments: ['@security.access.decision_manager']